module.exports={
    USER_COLLECTION:'user',
    ADMIN_COLLECTION:'admin',
    PRODUCT_COLLECTION:'products',
    CATEGORY_COLLECTION:'category',
    SUB_CATEGORY_COLLECTION:'subcategory',
    CART_COLLECTION:'cart',
    WISH_LIST_COLLECTION:'wishlist',
    BANNER_COLLECTION:'banner',
    ORDER_COLLECTION:'order',
    ADDRESS_COLLECTION:'address',
    COUPON_COLLECTION:'coupon'
}